### ISSUE TITLE
how to use setCanceledOnTouchOutside setCancelable

### ISSUE THREAD

**Issue by binu8051** [MarsadMaqsood/StylishDialogs#1]
if i click back button while the dialog is cancelled, how to overcome it.

Binu

**Comment by MarsadMaqsood** [comment]
`setCancelable(false)` used to prevent the dialog from dismissing when the back button pressed...
`setCanceledOnTouchOutside(false)` use to prevent the dialog from dismissing when pressed outside the dialog...

For example:
```
StylishAlertDialog alertDialog = new StylishAlertDialog(this,StylishAlertDialog.NORMAL);
alertDialog.setCancelable(false);
alertDialog.setCanceledOnTouchOutside(false);
alertDialog.show();
```
