### ISSUE TITLE
Button background is not changing

### ISSUE THREAD

**Issue by binu8051** [MarsadMaqsood/StylishDialogs#2]
Hi, i am using this library and the button color is not changing.
```
alertDialog.setConfirmButtonBackgroundColor(Color.RED);
alertDialog.setCancelButtonBackgroundColor(Color.GREEN);
```
All the 3 button color are same and its my primarycolor

But if i click and drag away the finger from the button i can see the button color.
please check it

Binu

**Comment by binu8051** [comment]
Reply me please.

**Comment by MarsadMaqsood** [comment]
@binu8051 
If you use the `Theme.MaterialComponents.DayNight.DarkActionBar` theme in the `themes.xml` file, the color will not change.

So use `Theme.AppCompat.`
because `MaterialTheme` uses `colorPrimary` as button color

**Comment by binu8051** [comment]
Thanks it worked
