### ISSUE TITLE
neutral button has bad view being at left

### ISSUE THREAD

**Issue by djdance** [MarsadMaqsood/StylishDialogs#3]
if you turn off cancel button, a neutral button looks cut off
![device-2021-09-16-110618](https://user-images.githubusercontent.com/2269720/133584801-46f7fced-4c66-4439-a0ef-b482738f3e59.png)

**Comment by MarsadMaqsood** [comment]
Thank you for pointing out this issue. I just fixed this issue in version `0.1.5`.
