### ISSUE TITLE
setOnCancelListener().show() is impossible

### ISSUE THREAD

**Issue by djdance** [MarsadMaqsood/StylishDialogs#5]
I can not add .show() to general setOnCancelListener() or setCancelable(false)

**Comment by MarsadMaqsood** [comment]
You can access `.show`, `etOnCancelListener()` `setCancelable(false)` using class object

```
        StylishAlertDialog stylishDialog = new StylishAlertDialog(...);

        stylishDialog.setCancelable(false);
        stylishDialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
            @Override
            public void onCancel(DialogInterface dialog) {

            }
        });

```

**Comment by djdance** [comment]
I know. I pointed that I can not write them all in chain like so:

```
new StylishAlertDialog(...)
     .setCancelable(false)
     .show()
```

Would you be so kind and add this ability? thanks!

**Comment by MarsadMaqsood** [comment]
Yes, you can write like a chain

use the latest version
For more visit [wiki page](https://github.com/MarsadMaqsood/StylishDialogs/wiki)

```java

new StylishAlertDialog(...)
     .setCancellable(false)
     .setCancelledOnTouchOutside(false)
     .show()

```
