### ISSUE TITLE
setConfirmButton is executed 3 times!

### ISSUE THREAD

**Issue by MoatzAtteya** [MarsadMaqsood/StylishDialogs#8]
first i want to thank you about this work and I want to notice you that any lines inside setConfirmButton listener is executed 3 times and may be 4 times.
I have tried this in many different ways and still got the problem.

**Comment by MarsadMaqsood** [comment]
> first i want to thank you about this work and I want to notice you that any lines inside setConfirmButton listener is executed 3 times and may be 4 times. I have tried this in many different ways and still got the problem.

Hi,
Could you please provide the code and steps to reproduce this issue? What version of this dependency are you using?

**Comment by MoatzAtteya** [comment]
![image](https://user-images.githubusercontent.com/86920482/198682391-5f5d9653-dbdc-492f-a636-d3fb01c567db.png)
and I'm using version 0.1.10
thank you for your replying.

**Comment by MarsadMaqsood** [comment]
👍 Fixed in version: `1.0.0`
